steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/interns-417211/mariam-web:v2', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/interns-417211/mariam-web:v2']

images:
  - 'gcr.io/interns-417211/mariam-web:v2'
