steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/interns-417211/weather-web:v3', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/interns-417211/weather-web:v3']

images:
  - 'gcr.io/interns-417211/weather-web:v3'
